DROP DATABASE minigur;
CREATE DATABASE IF NOT EXISTS minigur;
USE minigur;

CREATE TABLE IF NOT EXISTS UserCredentials (
  username VARCHAR(32),
  password VARCHAR(255),
  PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS User (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(32),
  is_admin BOOLEAN,
  PRIMARY KEY (id),
  FOREIGN KEY (username) REFERENCES UserCredentials (username) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Image (
  id INT(11) NOT NULL AUTO_INCREMENT,
  filename VARCHAR(256),
  title VARCHAR (256),
  upload_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  owner_user INT(11),
  PRIMARY KEY (id),
  FOREIGN KEY (owner_user) REFERENCES User (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Comment (
  id INT(11) NOT NULL AUTO_INCREMENT,
  comment_id VARCHAR (256),
  user_id INT(11),
  image_id INT(11),
  text TEXT,
  post_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE,
  FOREIGN KEY (image_id) REFERENCES Image (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Tag (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TagRelations (
  id INT(11) NOT NULL AUTO_INCREMENT,
  image_id INT(11),
  tag_id INT(11),
  user_id INT(11),
  PRIMARY KEY (id),
  FOREIGN KEY (image_id) REFERENCES Image (id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES Tag (id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Rating (
  user_id INT(11),
  image_id INT(11),
  is_upvote BOOLEAN,
  PRIMARY KEY (user_id, image_id),
  FOREIGN KEY (user_id) REFERENCES User (id)ON DELETE CASCADE,
  FOREIGN KEY (image_id) REFERENCES Image (id) ON DELETE CASCADE
);
